version: 0.2
phases:
  pre_build:
    commands:
     - sudo apt-get install zip unzip
     - chmod +x gradlew
  build:
    commands:
      - ./gradlew build
  post_build:
    commands:
      - cd build 
      - cp -rf * deploy
      - cd ..
      - cd deploy
      - zip -r codedeploy-$(date +%Y%m%d%H%m%S).zip *	  
artifacts:
  files:
    - deploy/codedeploy-$(date +%Y%m%d%H%m%S).zip
